// angular/src/app/modules/projects/issue-dialog/issue-dialog.component.ts
import {Component, Inject, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {IIssue, ISprint, IUser} from "../../core/models";
import {UserService} from "../../core/services/user.service";
import {MAT_DIALOG_DATA, MatDialogRef} from "@angular/material/dialog";
import {take} from "rxjs";
import {ProjectService} from "../../core/services/project.service";
import {ProjectStore} from "../project.store";
import {Status} from "../../core/enums/status.enum";

@Component({
  selector: 'app-issue-dialog',
  templateUrl: './issue-dialog.component.html',
  styleUrls: ['./issue-dialog.component.scss']
})
export class IssueDialogComponent implements OnInit {
  public form!: FormGroup;
  public developers!: IUser[];
  public sprints!: ISprint[];
  public statuses: {value: string, label: string}[] = Object.keys(Status).map((key) => ({value: key, label: Status[key]}));

  constructor(
      private fb: FormBuilder,
      private userService: UserService,
      private projectStore: ProjectStore,
      private projectService: ProjectService,
      private dialogRef: MatDialogRef<IssueDialogComponent>,
      @Inject(MAT_DIALOG_DATA) public data?: { issue: IIssue }
  ) { }

  ngOnInit(): void {
    this.form = this.fb.group({
      title: [this.data?.issue?.title ?? '', [Validators.required]],
      sprint: [this.data?.issue?.sprint ?? '', []],
      assignedTo: [this.data?.issue?.assignedTo ?? '', []],
      status: [this.data?.issue?.status ?? '', []],
      description: [this.data?.issue?.description ?? '', []],
      storyPoints: [this.data?.issue?.storyPoints ?? null, [Validators.min(0)]],
    })

    this.userService.getUsers({ role: 'developer'})
        .pipe(take(1))
        .subscribe((developers: IUser[]) => this.developers = developers);

    this.projectService.getAllSprints(this.projectStore.projectId)
      .pipe(take(1))
      .subscribe((sprints: ISprint[]) => this.sprints = sprints);
  }

  public confirm(): void {
    const data: IIssue = Object.assign({}, this.data?.issue, {...this.form.getRawValue()}) ;

    this.dialogRef.close(data);
  }

}

<form [formGroup]="form">
    <mat-card-content class="issue-container">
        <mat-form-field>
            <input formControlName="title" matInput placeholder="Title">
        </mat-form-field>

        <mat-form-field>
            <textarea formControlName="description" matInput placeholder="Description"></textarea>
        </mat-form-field>


        <mat-form-field>
            <mat-label>Assigned To</mat-label>
            <mat-select formControlName="assignedTo">
                <mat-option *ngFor="let user of developers" [value]="user.id">{{user.firstName + ' ' + user.lastName}}</mat-option>
            </mat-select>
        </mat-form-field>

        <mat-form-field>
            <mat-label>Sprint</mat-label>
            <mat-select formControlName="sprint">
                <mat-option *ngFor="let sprint of sprints" [value]="sprint.id">{{sprint.title}}</mat-option>
            </mat-select>
        </mat-form-field>

      <mat-form-field>
        <mat-label>Status</mat-label>
        <mat-select formControlName="status">
          <mat-option *ngFor="let status of statuses" [value]="status.value">{{status.label}}</mat-option>
        </mat-select>
      </mat-form-field>

        <mat-form-field>
            <input type="number" formControlName="storyPoints" matInput placeholder="Story points">
        </mat-form-field>
    </mat-card-content>

    <mat-card-actions>
        <button [disabled]="form.invalid" class="register" mat-raised-button color="primary" (click)="confirm()">Confirm</button>
        <button mat-raised-button color="warn" [mat-dialog-close]="false">Cancel</button>
    </mat-card-actions>
</form>

// ui-react/src/components/my-project/issue-dialog/IssueDialog.tsx
import {
    Button,
    Dialog,
    DialogActions,
    DialogContent,
    DialogTitle,
    FormControl,
    InputLabel,
    MenuItem,
    OutlinedInput,
    Select,
    TextField
} from "@mui/material"
import {FC, memo, useCallback, useEffect, useMemo, useRef, useState} from "react";
import {useIssue} from "../../../store/issues/issues.hooks";
import styles from "./IssueDialogl.module.scss";
import {IIssue, ISprint, IUser} from "../../../models";
import {UserApi} from "../../../api/user.api";
import {SprintApi} from "../../../api/sprint.api";
import {useProject} from "../../../store/projects/projects.hooks";
import {Status} from "../../../shared/status.enum";

interface IssueDialogProps {
    open: boolean,
    onClose: (issue: IIssue | null) => void
}

const IssueDialog: FC<IssueDialogProps> = ({open = false, onClose}) => {
    const issue = useIssue();
    const project = useProject();
    const formRef = useRef(null);

    const [state, setState] = useState<IIssue>({
        title: '',
        description: '',
        assignedTo: '',
        deleted: false,
        id: '',
        storyPoints: 0,
        project: '',
        sprint: '',
        status: '',
        addedBy: '',
    });
    const [developers, setDevelopers] = useState<IUser[]>([]);
    const [sprints, setSprints] = useState<ISprint[]>([]);
    const statuses = useMemo(() => Object.keys(Status).map((key) => ({value: key, label: Status[key]})), [])

    useEffect(() => {
        if (issue) {
            setState(issue);
        }
    }, [issue])

    useEffect(() => {
        UserApi.getUsers({role: 'developer'}).then((res) => setDevelopers(res));
        SprintApi.getAllSprints(project.id).then((res) => setSprints(res))
    }, [project])

    const updateState = useCallback((e: { target: { value: any, name: string } }) => {
        setState(prev => ({...prev, [e.target.name]: e.target.value}));
    }, [])

    const closeHandler = useCallback((submit: boolean) => () => {
        onClose(submit ? state : null);
    }, [onClose, state]);

    return <Dialog open={open} onClose={closeHandler(false)}>
        <DialogTitle>{issue ? 'Edit issue' : 'Create issue'}</DialogTitle>
        <DialogContent>
            <form className={styles.form} ref={formRef}>
                <FormControl>
                    <TextField value={state?.title} onChange={updateState} label='Title' name='title'/>
                    {/*<FormHelperText className={styles.error}>must be between 3 and 128 characters no special*/}
                    {/*    symbols</FormHelperText>*/}
                </FormControl>
                <FormControl>
                    <TextField name='description' value={state?.description} onChange={updateState}
                               label='Description'
                               id='description'/>
                </FormControl>
                <FormControl>
                    <InputLabel>Assigned To</InputLabel>
                    <Select
                        name="assignedTo"
                        value={state?.assignedTo}
                        onChange={updateState}
                        input={<OutlinedInput label="Assigned To"/>}
                    >
                        {developers.map((developer) => (
                            <MenuItem
                                key={developer.id}
                                value={developer.id}
                            >
                                {developer.firstName + ' ' + developer.lastName}
                            </MenuItem>
                        ))}
                    </Select>
                </FormControl>
                <FormControl>
                    <InputLabel>Sprint</InputLabel>
                    <Select
                        name="team"
                        value={state?.sprint}
                        onChange={updateState}
                        input={<OutlinedInput label="Sprint"/>}
                    >
                        {sprints.map((sprint) => (
                            <MenuItem
                                key={sprint.id}
                                value={sprint.id}
                            >
                                {sprint.title}
                            </MenuItem>
                        ))}
                    </Select>
                </FormControl>
                <FormControl>
                    <TextField name='storyPoints' type='number' value={state?.storyPoints} onChange={updateState}
                               label='Story points'
                               id='description'/>
                </FormControl>
                <FormControl>
                    <InputLabel>Status</InputLabel>
                    <Select
                        name="status"
                        value={state?.status}
                        onChange={updateState}
                        input={<OutlinedInput label="Status"/>}
                    >
                        {statuses.map((status) => (
                            <MenuItem
                                key={status.value}
                                value={status.value}
                            >
                                {status.label}
                            </MenuItem>
                        ))}
                    </Select>
                </FormControl>
            </form>
        </DialogContent>
        <DialogActions>
            <Button onClick={closeHandler(true)}>Submit</Button>
            <Button onClick={closeHandler(false)}>Cancel</Button>
        </DialogActions>
    </Dialog>
}

export default memo(IssueDialog)
